export enum ChainId {
  Mainnet = 1,
  Ropsten = 3,
  Rinkeby = 4,
  BSC_Test = 97,
  BSC = 56,
  Optimistic = 10,
  xDai = 100,
  Fuse = 122,
  Fantom = 250,
  Boba = 288,
  Polygon = 137,
  Mumbai = 80001,
  Conflux = 1030,
  Arbiturm = 42161,
  Celo = 42220,
  Avalanche = 43114,
  Aurora = 1313161554,
  Metis = 1088,
  Metis_test = 28,
  Moonriver = 1285,
  Conflux_test = 71,
  Harmony = 1666600000,
  Harmony_test = 1666700000,
}

export const BlockExplorer: Map<string, string> = new Map([
  ["Mainnet", "https://etherscan.io/address/"],
  ["Ropsten", "https://ropsten.etherscan.io/address/"],
  ["Rinkeby", "https://rinkeby.etherscan.io/address/"],
  ["BSC_Test", "https://testnet.bscscan.com/address/"],
  ["BSC", "https://bscscan.com/address/"],
  ["Optimistic", "https://optimistic.etherscan.io/address/"],
  ["xDai", "https://blockscout.com/xdai/mainnet/address/"],
  ["Fuse", "https://explorer.fuse.io/address/"],
  ["Fantom", "https://ftmscan.com/address/"],
  ["Boba","https://blockexplorer.boba.network/address/"],
  ["Polygon", "https://polygonscan.com/address/"],
  ["Conflux", "https://evm.confluxscan.io/address/"],
  ["Conflux_test", "https://evmtestnet.confluxscan.io/address/"],
  ["Arbiturm","https://explorer.arbitrum.io/address/"],
  ["Celo","https://explorer.celo.org/address/"],
  ["Avalanche", "https://snowtrace.io/address/"],
  ["Aurora","https://explorer.mainnet.aurora.dev/address/"],
  ["Metis","https://andromeda-explorer.metis.io/address/"],
  ["Metis_test", "https://stardust-explorer.metis.io/address/"],
  ["Moonriver","https://moonriver.moonscan.io/address/"],
  ["Harmony", "https://explorer.harmony.one/address/"],
  ["Harmony_test", "https://explorer.pops.one/address/"],
])

export const Contracts: Array<string> = [
  "MysteryBox",
  "MaskTestNFT",
  "WhitelistQlf",
  "SigVerifyQlf",
  "MaskHolderQlf",
  "MerkleProofQlf"
]
